mysite/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register_request, name='register'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('feed/', views.feed, name='feed'),
    path('settings/', views.edit_profile, name='edit_profile'),
    path('search_results/', views.search_results, name='search_results'),
    path('top_profiles', views.top_profiles_list, name='top_profiles'),
    path('profile/<str:username>/', views.profile, name='user_profile'),
    path('profile/<str:username>/follow', views.add_follower, name='add_follower'),
    path('profile/<str:username>/unfollow', views.remove_follower, name='remove_follower'),
    path('profile/<str:username>/top/<int:top_id>/', views.profile_top_detail, name='profile_top_detail'),
    path('profile/<str:username>/bottom/<int:bottom_id>/', views.profile_bottom_detail, name='profile_bottom_detail'),
    path('profile/<str:username>/outerwear/<int:outerwear_id>/', views.profile_outerwear_detail, name='profile_outerwear_detail'),
    path('profile/<str:username>/footwear/<int:footwear_id>/', views.profile_footwear_detail, name='profile_footwear_detail'),
    path('profile/<str:username>/accessory/<int:accessory_id>/', views.profile_accessory_detail, name='profile_accessory_detail'),
    path('profile/<str:username>/outfit/<int:outfit_id>/', views.profile_outfit_detail, name='profile_outfit_detail'),
    path('inbox/', views.inbox, name='inbox'),
    path('inbox/<int:message_id>/', views.inbox_detail, name='inbox_detail'),
    path('sent/', views.sent, name='sent'),
    path('sent/<int:message_id>/', views.sent_detail, name='sent_detail'),
    path('profile/<str:username>/message/', views.send_message, name='send_message'),
    path('inbox/<str:username>/reply/', views.reply_message, name='reply_message'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('wardrobe/', include('wardrobe.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/wardrobe/urls.py
from django.urls import path
from . import views

app_name = 'wardrobe'

urlpatterns = [
    path('', views.wardrobe, name='wardrobe'),
    # Garment Upload
    path('top/upload/', views.top_upload, name='top_upload'),
    path('bottom/upload/', views.bottom_upload, name='bottom_upload'),
    path('outerwear/upload/', views.outerwear_upload, name='outerwear_upload'),
    path('footwear/upload/', views.footwear_upload, name='footwear_upload'),
    path('accessory/upload/', views.accessory_upload, name='accessory_upload'),
    # Garment Detail
    path('top/<int:top_id>/', views.top_detail, name='top_detail'),
    path('bottom/<int:bottom_id>/', views.bottom_detail, name='bottom_detail'),
    path('outerwear/<int:outerwear_id>/', views.outerwear_detail, name='outerwear_detail'),
    path('footwear/<int:footwear_id>/', views.footwear_detail, name='footwear_detail'),
    path('accessory/<int:accessory_id>/', views.accessory_detail, name='accessory_detail'),
    # Garment Edit
    path('top/<int:top_id>/edit/', views.top_edit, name='top_edit'),
    path('bottom/<int:bottom_id>/edit/', views.bottom_edit, name='bottom_edit'),
    path('outerwear/<int:outerwear_id>/edit/', views.outerwear_edit, name='outerwear_edit'),
    path('footwear/<int:footwear_id>/edit/', views.footwear_edit, name='footwear_edit'),
    path('accessory/<int:accessory_id>/edit/', views.accessory_edit, name='accessory_edit'),
    # Garment Delete
    path('top/<int:top_id>/delete/', views.top_delete, name='top_delete'),
    path('bottom/<int:bottom_id>/delete/', views.bottom_delete, name='bottom_delete'),
    path('outerwear/<int:outerwear_id>/delete/', views.outerwear_delete, name='outerwear_delete'),
    path('footwear/<int:footwear_id>/delete/', views.footwear_delete, name='footwear_delete'),
    path('accessory/<int:accessory_id>/delete/', views.accessory_delete, name='accessory_delete'),
    # Outfit
    path('outfit/create/', views.outfit_create, name='outfit_create'),
    path('outfit/<int:outfit_id>/', views.outfit_detail, name='outfit_detail'),
    path('outfit/<int:outfit_id>/edit/', views.outfit_edit, name='outfit_edit'),
    path('outfit/<int:outfit_id>/delete/', views.outfit_delete, name='outfit_delete'),
]

mysite/wardrobe/forms.py
from django import forms
from django.utils.safestring import mark_safe
from .models import Outfit, Top, Bottom, Outerwear, Footwear, Accessory
  
class TopForm(forms.ModelForm):
    class Meta:
        model = Top
        fields = ['name', 'image', 'description']

class BottomForm(forms.ModelForm):
    class Meta:
        model = Bottom
        fields = ['name', 'image', 'description']

class OuterwearForm(forms.ModelForm):
    class Meta:
        model = Outerwear
        fields = ['name', 'image', 'description']

class FootwearForm(forms.ModelForm):
    class Meta:
        model = Footwear
        fields = ['name', 'image', 'description']

class AccessoryForm(forms.ModelForm):
    class Meta:
        model = Accessory
        fields = ['name', 'image', 'description']

class CustomMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return mark_safe("<div class='card'><img src='%s' class='card-img-top' alt='garment'><div class='card-body'><p class='card-text'>%s</p></div></div>"
                            % (obj.image.url, obj.name))

class OutfitForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(OutfitForm, self).__init__(*args, **kwargs)
        self.fields['tops'].queryset = Top.objects.filter(user=self.request.user)
        self.fields['bottoms'].queryset = Bottom.objects.filter(user=self.request.user)
        self.fields['outerwear'].queryset = Outerwear.objects.filter(user=self.request.user)
        self.fields['footwear'].queryset = Footwear.objects.filter(user=self.request.user)
        self.fields['accessories'].queryset = Accessory.objects.filter(user=self.request.user)
    
    class Meta:
        model = Outfit
        fields = ['name', 'image', 'description', 'tops', 'bottoms', 'outerwear', 'footwear', 'accessories']

    tops = CustomMultipleChoiceField(
        queryset=None,
        widget=forms.CheckboxSelectMultiple,
        required=False)

    bottoms = CustomMultipleChoiceField(
        queryset=None,
        widget=forms.CheckboxSelectMultiple,
        required=False)

    outerwear = CustomMultipleChoiceField(
        queryset=None,
        widget=forms.CheckboxSelectMultiple,
        required=False)
    
    footwear = CustomMultipleChoiceField(
        queryset=None,
        widget=forms.CheckboxSelectMultiple,
        required=False)

    accessories = CustomMultipleChoiceField(
        queryset=None,
        widget=forms.CheckboxSelectMultiple,
        required=False)

mysite/wardrobe/views.py
from unicodedata import category, name
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from .models import Outfit, Top, Bottom, Outerwear, Footwear, Accessory
from .forms import OutfitForm, TopForm, BottomForm, OuterwearForm, FootwearForm, AccessoryForm

# Create your views here.
@login_required(login_url='/login')
def wardrobe(request):
    top_list = Top.objects.select_related().filter(user=request.user).order_by('-date')
    bottom_list = Bottom.objects.select_related().filter(user=request.user).order_by('-date')
    outerwear_list = Outerwear.objects.select_related().filter(user=request.user).order_by('-date')
    footwear_list = Footwear.objects.select_related().filter(user=request.user).order_by('-date')
    accessory_list = Accessory.objects.select_related().filter(user=request.user).order_by('-date')
    outfit_list = Outfit.objects.select_related().filter(user=request.user).order_by('-date')

    context = {
        'top_list': top_list,
        'bottom_list': bottom_list,
        'outerwear_list': outerwear_list, 
        'footwear_list': footwear_list, 
        'accessory_list': accessory_list, 
        'outfit_list': outfit_list,
        'nbar': 'wardrobe',
    }
    
    return render(request, 'wardrobe/wardrobe.html', context)

# Garment Upload Functions
@login_required(login_url='/login')
def top_upload(request):
    if request.method == 'POST':
        form = TopForm(request.POST, request.FILES)
        if form.is_valid():
            garment = form.save(commit=False)
            garment.user = request.user
            garment.save()
            return redirect('wardrobe:wardrobe')
    else:
        form = TopForm()
    return render(request, 'wardrobe/garment_form.html', {'form': form, 'category': 'top'})

@login_required(login_url='/login')
def bottom_upload(request):
    if request.method == 'POST':
        form = BottomForm(request.POST, request.FILES)
        if form.is_valid():
            garment = form.save(commit=False)
            garment.user = request.user
            garment.save()
            return redirect('wardrobe:wardrobe')
    else:
        form = BottomForm()
    return render(request, 'wardrobe/garment_form.html', {'form': form, 'category': 'bottom'})

@login_required(login_url='/login')
def outerwear_upload(request):
    if request.method == 'POST':
        form = OuterwearForm(request.POST, request.FILES)
        if form.is_valid():
            garment = form.save(commit=False)
            garment.user = request.user
            garment.save()
            return redirect('wardrobe:wardrobe')
    else:
        form = OuterwearForm()
    return render(request, 'wardrobe/garment_form.html', {'form': form, 'category': 'outerwear'})

@login_required(login_url='/login')
def footwear_upload(request):
    if request.method == 'POST':
        form = FootwearForm(request.POST, request.FILES)
        if form.is_valid():
            garment = form.save(commit=False)
            garment.user = request.user
            garment.save()
            return redirect('wardrobe:wardrobe')
    else:
        form = FootwearForm()
    return render(request, 'wardrobe/garment_form.html', {'form': form, 'category': 'footwear'})

@login_required(login_url='/login')
def accessory_upload(request):
    if request.method == 'POST':
        form = AccessoryForm(request.POST, request.FILES)
        if form.is_valid():
            garment = form.save(commit=False)
            garment.user = request.user
            garment.save()
            return redirect('wardrobe:wardrobe')
    else:
        form = AccessoryForm()
    return render(request, 'wardrobe/garment_form.html', {'form': form, 'category': 'accessory'})

# Garment Detail Functions
@login_required(login_url='/login')
def top_detail(request, top_id):
    top = get_object_or_404(Top, pk=top_id)
    return render(request, 'wardrobe/garment_detail.html', {'garment': top, 'category': 'top'})

@login_required(login_url='/login')
def bottom_detail(request, bottom_id):
    bottom = get_object_or_404(Bottom, pk=bottom_id)
    return render(request, 'wardrobe/garment_detail.html', {'garment': bottom, 'category': 'bottom'})

@login_required(login_url='/login')
def outerwear_detail(request, outerwear_id):
    outerwear = get_object_or_404(Outerwear, pk=outerwear_id)
    return render(request, 'wardrobe/garment_detail.html', {'garment': outerwear, 'category': 'outerwear'})

@login_required(login_url='/login')
def footwear_detail(request, footwear_id):
    footwear = get_object_or_404(Footwear, pk=footwear_id)
    return render(request, 'wardrobe/garment_detail.html', {'garment': footwear, 'category': 'footwear'})

@login_required(login_url='/login')
def accessory_detail(request, accessory_id):
    accessory = get_object_or_404(Accessory, pk=accessory_id)
    return render(request, 'wardrobe/garment_detail.html', {'garment': accessory, 'category': 'accessory'})

# Garment Edit Functions
@login_required(login_url='/login')
def top_edit(request, top_id):
    record = get_object_or_404(Top, user=request.user, pk=top_id)
    if request.method == 'POST':
        form = TopForm(request.POST, files=request.FILES, instance=record)
        if form.is_valid():
            form.save()
            return redirect('wardrobe:top_detail', top_id)
    else:
        form = TopForm(instance=record)
    return render(request, 'wardrobe/garment_edit.html', {'form': form, 'garment_id': top_id, 'category': 'top'})

@login_required(login_url='/login')
def bottom_edit(request, bottom_id):
    record = get_object_or_404(Bottom, user=request.user, pk=bottom_id)
    if request.method == 'POST':
        form = BottomForm(request.POST, files=request.FILES, instance=record)
        if form.is_valid():
            form.save()
            return redirect('wardrobe:bottom_detail', bottom_id)
    else:
        form = BottomForm(instance=record)
    return render(request, 'wardrobe/garment_edit.html', {'form': form, 'garment_id': bottom_id, 'category': 'bottom'})

@login_required(login_url='/login')
def outerwear_edit(request, outerwear_id):
    record = get_object_or_404(Outerwear, user=request.user, pk=outerwear_id)
    if request.method == 'POST':
        form = OuterwearForm(request.POST, files=request.FILES, instance=record)
        if form.is_valid():
            form.save()
            return redirect('wardrobe:outerwear_detail', outerwear_id)
    else:
        form = OuterwearForm(instance=record)
    return render(request, 'wardrobe/garment_edit.html', {'form': form, 'garment_id': outerwear_id, 'category': 'outerwear'})

@login_required(login_url='/login')
def footwear_edit(request, footwear_id):
    record = get_object_or_404(Footwear, user=request.user, pk=footwear_id)
    if request.method == 'POST':
        form = FootwearForm(request.POST, files=request.FILES, instance=record)
        if form.is_valid():
            form.save()
            return redirect('wardrobe:footwear_detail', footwear_id)
    else:
        form = FootwearForm(instance=record)
    return render(request, 'wardrobe/garment_edit.html', {'form': form, 'garment_id': footwear_id, 'category': 'footwear'})

@login_required(login_url='/login')
def accessory_edit(request, accessory_id):
    record = get_object_or_404(Accessory, user=request.user, pk=accessory_id)
    if request.method == 'POST':
        form = AccessoryForm(request.POST, files=request.FILES, instance=record)
        if form.is_valid():
            form.save()
            return redirect('wardrobe:accessory_detail', accessory_id)
    else:
        form = AccessoryForm(instance=record)
    return render(request, 'wardrobe/garment_edit.html', {'form': form, 'garment_id': accessory_id, 'category': 'accessory'})

# Garment Delete Functions
@login_required(login_url='/login')
def top_delete(request, top_id):
    record = get_object_or_404(Top, user=request.user, pk=top_id)
    if request.method == 'POST':
        record.delete()
    return redirect('wardrobe:wardrobe')

@login_required(login_url='/login')
def bottom_delete(request, bottom_id):
    record = get_object_or_404(Bottom, user=request.user, pk=bottom_id)
    if request.method == 'POST':
        record.delete()
    return redirect('wardrobe:wardrobe')

@login_required(login_url='/login')
def outerwear_delete(request, outerwear_id):
    record = get_object_or_404(Outerwear, user=request.user, pk=outerwear_id)
    if request.method == 'POST':
        record.delete()
    return redirect('wardrobe:wardrobe')

@login_required(login_url='/login')
def footwear_delete(request, footwear_id):
    record = get_object_or_404(Footwear, user=request.user, pk=footwear_id)
    if request.method == 'POST':
        record.delete()
    return redirect('wardrobe:wardrobe')

@login_required(login_url='/login')
def accessory_delete(request, accessory_id):
    record = get_object_or_404(Accessory, user=request.user, pk=accessory_id)
    if request.method == 'POST':
        record.delete()
    return redirect('wardrobe:wardrobe')

# Outfit Functions
@login_required(login_url='/login')
def outfit_create(request):
    if request.method == 'POST':
        form = OutfitForm(request.POST, request.FILES, request=request)
        if form.is_valid():
            outfit = form.save(commit=False)
            outfit.user = request.user
            outfit.save()
            form.save_m2m()
            return redirect('wardrobe:wardrobe')
    else:
        form = OutfitForm(request=request)
    return render(request, 'wardrobe/outfit_form.html', {'form': form})

@login_required(login_url='/login')
def outfit_detail(request, outfit_id):
    outfit = get_object_or_404(Outfit, pk=outfit_id)
    return render(request, 'wardrobe/outfit_detail.html', {'outfit': outfit})

@login_required(login_url='/login')
def outfit_edit(request, outfit_id):
    record = get_object_or_404(Outfit, user=request.user, pk=outfit_id)

mysite/wardrobe/templates/wardrobe/garment_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ garment.name }}{% endblock %}

{% block content %}

<!--Garment_detail-->
<div class="container py-5">
    <div class="row">
        <div class="col-lg-6 col-md-10 mx-auto">

            <h1 class="display-4">{{ garment.name }}</h1>

            <figure class="figure">
                <img src="{{ garment.image.url }}" class="figure-img img-fluid rounded">
                <figcaption class="figure-caption">Category: {{ category|title }}</figcaption>
            </figure>

            <p>{{ garment.description }}</p>

            <div>
                <a class="btn btn-secondary" href="{% url 'wardrobe:wardrobe' %}" role="button">Back</a>
                {% if category == 'top' %}
                <a class="btn btn-primary" href="{% url 'wardrobe:top_edit' garment.id %}" role="button">Edit</a>
                {% elif category == 'bottom' %}
                <a class="btn btn-primary" href="{% url 'wardrobe:bottom_edit' garment.id %}" role="button">Edit</a>
                {% elif category == 'outerwear' %}
                <a class="btn btn-primary" href="{% url 'wardrobe:outerwear_edit' garment.id %}" role="button">Edit</a>
                {% elif category == 'footwear' %}
                <a class="btn btn-primary" href="{% url 'wardrobe:footwear_edit' garment.id %}" role="button">Edit</a>
                {% elif category == 'accessory' %}
                <a class="btn btn-primary" href="{% url 'wardrobe:accessory_edit' garment.id %}" role="button">Edit</a>
                {% endif %}

                <!-- Button trigger modal -->
                <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                    data-bs-target="#garmentDeleteModal">Delete</button>
                <!-- Modal -->
                <div class="modal fade" id="garmentDeleteModal" tabindex="-1" aria-labelledby="garmentDeleteModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="garmentDeleteModalLabel">Delete {{ category|title }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                Are you sure you want to delete this item?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                {% if category == 'top' %}
                                <form action="{% url 'wardrobe:top_delete' garment.id %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn btn-danger">Delete</button>
                                </form>
                                {% elif category == 'bottom' %}
                                <form action="{% url 'wardrobe:bottom_delete' garment.id %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn btn-danger">Delete</button>
                                </form>
                                {% elif category == 'outerwear' %}
                                <form action="{% url 'wardrobe:outerwear_delete' garment.id %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn btn-danger">Delete</button>
                                </form>
                                {% elif category == 'footwear' %}
                                <form action="{% url 'wardrobe:footwear_delete' garment.id %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn btn-danger">Delete</button>
                                </form>
                                {% elif category == 'accessory' %}
                                <form action="{% url 'wardrobe:accessory_delete' garment.id %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn btn-danger">Delete</button>
                                </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

mysite/wardrobe/templates/wardrobe/garment_edit.html
{% extends 'core/base.html' %}

{% block title %}Edit Garment{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<!--Garment_edit-->
<div class="container py-5">
    <h1 class="display-1">Edit {{category|title}}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        {% if category == 'top' %}
        <a class="btn btn-secondary" href="{% url 'wardrobe:top_detail' garment_id %}" role="button">Back</a>
        {% elif category == 'bottom' %}
        <a class="btn btn-secondary" href="{% url 'wardrobe:bottom_detail' garment_id %}" role="button">Back</a>
        {% elif category == 'outerwear' %}
        <a class="btn btn-secondary" href="{% url 'wardrobe:outerwear_detail' garment_id %}" role="button">Back</a>
        {% elif category == 'footwear' %}
        <a class="btn btn-secondary" href="{% url 'wardrobe:footwear_detail' garment_id %}" role="button">Back</a>
        {% elif category == 'accessory' %}
        <a class="btn btn-secondary" href="{% url 'wardrobe:accessory_detail' garment_id %}" role="button">Back</a>
        {% endif %}
        <button class="btn btn-primary" type="submit">Edit</button>
    </form>
</div>

{% endblock %}

mysite/wardrobe/templates/wardrobe/wardrobe.html
{% extends 'core/base.html' %}

{% block title %}Wardrobe{% endblock %}

{% block content %}

<!--Wardrobe-->
<div class="container py-4">
    <h1 class="display-1">Wardrobe</h1>

    <hr>

    <div class="row align-items-center">
        <div class="col">
            <h1>Outfits</h1>
        </div>
        <div class="col">
            <a class="btn btn-primary float-end" href="{% url 'wardrobe:outfit_create' %}" role="button">Create</a>
        </div>
    </div>

    <div class="py-3">
        {% if outfit_list %}
        <div class="col col-lg-6 mx-auto">
            <div id="outfitCarousel" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    {% for outfit in outfit_list %}
                    {% if forloop.first %}
                    <div class="carousel-item active">
                        <a class="text-decoration-none text-reset" href="{% url 'wardrobe:outfit_detail' outfit.id %}">
                            <img src="{{ outfit.image.url }}" class="d-block w-100" alt="Outfit">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>{{ outfit.name }}</h5>
                                <p>{{ outfit.description }}</p>
                            </div>
                        </a>
                    </div>
                    {% else %}
                    <div class="carousel-item">
                        <a class="text-decoration-none text-reset" href="{% url 'wardrobe:outfit_detail' outfit.id %}">
                            <img src="{{ outfit.image.url }}" class="d-block w-100" alt="Outfit">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>{{ outfit.name }}</h5>
                                <p>{{ outfit.description }}</p>
                            </div>
                        </a>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#outfitCarousel"
                    data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#outfitCarousel"
                    data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        {% else %}
        <p>No outfits created.</p>
        {% endif %}
    </div>

    <hr>

    <div class="row align-items-center">
        <div class="col">
            <h1>Garments</h1>
        </div>
        <div class="col">
            <div class="dropdown">
                <button class="btn btn-primary float-end dropdown-toggle" type="button" id="dropdownMenuButton1"
                    data-bs-toggle="dropdown" aria-expanded="false">Add</button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><a class="dropdown-item" href="{% url 'wardrobe:top_upload' %}">Top</a></li>
                    <li><a class="dropdown-item" href="{% url 'wardrobe:bottom_upload' %}">Bottom</a></li>
                    <li><a class="dropdown-item" href="{% url 'wardrobe:outerwear_upload' %}">Outerwear</a></li>
                    <li><a class="dropdown-item" href="{% url 'wardrobe:footwear_upload' %}">Footwear</a></li>
                    <li><a class="dropdown-item" href="{% url 'wardrobe:accessory_upload' %}">Accessory</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="pt-1">
        {% if top_list or bottom_list or outerwear_list or footwear_list or accessory_list %}

        {% if top_list %}
        <div class="mb-4">
            <p>Tops:</p>
            <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
                {% for garment in top_list %}
                <div class="col">
                    <a class="text-decoration-none text-reset" href="{% url 'wardrobe:top_detail' garment.id %}">
                        <div class="card h-100">
                            <img src="{{ garment.image.url }}" class="card-img-top" alt="Top">
                            <div class="card-body">
                                <h6 class="card-title text-truncate">{{ garment.name }}</h6>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% if bottom_list %}
        <div class="mb-4">
            <p>Bottoms:</p>
            <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
                {% for garment in bottom_list %}
                <div class="col">
                    <a class="text-decoration-none text-reset" href="{% url 'wardrobe:bottom_detail' garment.id %}">
                        <div class="card h-100">
                            <img src="{{ garment.image.url }}" class="card-img-top" alt="Bottom">
                            <div class="card-body">
                                <h6 class="card-title text-truncate">{{ garment.name }}</h6>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% if outerwear_list %}
        <div class="mb-4">
            <p>Outerwear:</p>
            <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
                {% for garment in outerwear_list %}
                <div class="col">
                    <a class="text-decoration-none text-reset" href="{% url 'wardrobe:outerwear_detail' garment.id %}">
                        <div class="card h-100">
                            <img src="{{ garment.image.url }}" class="card-img-top" alt="Outerwear">
                            <div class="card-body">
                                <h6 class="card-title text-truncate">{{ garment.name }}</h6>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% if footwear_list %}
        <div class="mb-4">
            <p>Footwear:</p>
            <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
                {% for garment in footwear_list %}
                <div class="col">
                    <a class="text-decoration-none text-reset" href="{% url 'wardrobe:footwear_detail' garment.id %}">
                        <div class="card h-100">
                            <img src="{{ garment.image.url }}" class="card-img-top" alt="Footwear">
                            <div class="card-body">
                                <h6 class="card-title text-truncate">{{ garment.name }}</h6>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% if accessory_list %}
        <div class="mb-4">
            <p>Accessories:</p>
            <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
                {% for garment in accessory_list %}
                <div class="col">
                    <a class="text-decoration-none text-reset" href="{% url 'wardrobe:accessory_detail' garment.id %}">
                        <div class="card h-100">
                            <img src="{{ garment.image.url }}" class="card-img-top" alt="Accessory">
                            <div class="card-body">
                                <h6 class="card-title text-truncate">{{ garment.name }}</h6>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% else %}
        <p class="mt-3">No garments added.</p>
        {% endif %}
    </div>
</div>

{% endblock %}